name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: toggle workflow command echoing
        run: echo " Running a script file " 
        shell: bash
      - name: pre-commti
        run: |
          mkdir new
          ls -l
             
