name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: toggle workflow command echoing
        run: echo " Running a script file " 
        shell: bash
      - name: pre-commit
        run: |
          mkdir new
          pwd
          cd /
          ls -l
      - name: pretest
        run: ./test.sh 
             
